FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt && pip install --no-cache-dir pytest

COPY . .

ENV PYTHONUNBUFFERED=1

CMD ["python", "run_pipeline_v2.py"]
